config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :posts
  resources :categories
  resources :works
  resources :products
  resources :company_association_files
  resources :contacts
  
  get 'news'=>'news#index'
  get 'company'=>'company#index'
  get 'our_works'=>'our_works#index'
  get 'company/pdf_viewer'
  get 'our_works/gallery'
  get 'home/gallery'
  get 'home/manage'
  get 'contacts/success'
  root 'home#index'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  @current_user = http_basic_authenticate_with name:"admin", password:"admin",except: [:index, :gallery]
  before_action :set_product, only: %i[ gallery ]
  def index
    @pagy, @categories = pagy(Category.all)
    @title = "Home"
  end

  def manage
    @title = "Manage"
  end

  def gallery
  end

  def set_product
    @pagy, @product = pagy(Product.where(category_id: params[:cat_id]))
    @cat_title = Category.find(params[:cat_id])
    @title = "Gallery"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer_container">
    <div class="footer-img">
        <%= image_tag("logo/info_img.jpeg", alt: "logo img")%>
    </div>
    <div class="footer-info">
        <p class="text">www.edilsviluppo.com</p>
        <p>Tel <span>324 6123960</span> &bull; <span>335 6562064</span></p>
    </div>
</footer>

app/views/home/_header.html.erb
<header class="header_container">
    <nav class="menu_bar_container">
        <div class="menu_nav_container">
            <button class="app_img_bt">
                
                <%= image_tag("icons/app_menu.png", id: "app_img_id", class: "app_img_menu", alt: "app menu") %>
            </button>
            <button class="icon-home-bt">
                <%= link_to image_tag("icons/home.png",alt: "home image" ,class:"icon-home-img"), root_path %>
            </button>
            <ul id="list_menu" class="display_menu">
                <li class="li_home_link"><%= link_to t(".home"), root_path %></li>
                <li><%= link_to t(".our_work"), our_works_path %></li>
                <li><%= link_to t(".company"), company_path %></li>
                <li><%= link_to t(".news"), news_path %></li>
                <li><%= link_to t(".contacts"), contacts_path%></li>
                <li><%= link_to t(".manage"), home_manage_path%></li>
            </ul>
        </div>

        <div class="language_img_cont">
        <div class="languages_container">
            <div class="languages_sub_container">
                <p id="languages_p"><%= t(".country_code")%></p>
                <div class="languages_img"> <%= image_tag("icons/down-arrow.png", id: "languages_img") %></div>
            </div>
            <ul class="languages_ul display_none">
                <li><%= link_to "English",root_path(locale: :en)%></li>
                <li><%= link_to "Italiano",root_path(locale: :it)%></li>
            </ul>
        </div>
        <div class="additional_img_container">
            <%= image_tag('logo/40_years_logo.png', alt: 'logo image')%>
        </div>
        </div>

    </nav>
    <div class="img-logo-container">
        <%= image_tag("logo/logo.png", alt: 'logo image')%>
    </div>
</header>

app/views/home/gallery.html.erb
<div class="gallery_main_show_container">
    <% if !@product.empty? %>
    <h2><%= @cat_title.title %></h2>
    <% @product.each do |p| %>
    <div class="gallery_detail_container">
        <div class="gallery_img_container">
        <% if p.product_img.attached? %>
        <%= image_tag p.product_img %>
        <% end %>
        </div>
        <header class="gallery_description_container">
            <h3><%= p.description %></h3>
        </header>
    </div>
    <% end %>
    <% else %>
    <h1>Sorry gallery is in working state<h1>
    <% end %> 
</div>
<div class="nav-pagy-container">
    <% if @product.count > 0%>
    <p><%=if @pagy.page == @pagy.last then @product.count else @pagy.items*@pagy.page end%>/<%= @product.count %></p>
    <%end%>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %> 
</div>

app/views/home/index.html.erb
<h1 class="home_h1_heder"><%= t(".head_title_home") %></h1>
<div class="main_show_container">
    <% @categories.each do |category| %>
    <div class="detail_container">
        <div class="img_container">
        <% if category.category_img.attached? %>
        <%= link_to image_tag(category.category_img), home_gallery_path(cat_id: category.id)%>
        <% end %>
        </div>
        <header class="description_container">
            <h2><%= link_to category.title, home_gallery_path(cat_id: category.id)%></h2>
            <p><%= link_to category.description, home_gallery_path(cat_id: category.id)%></p>
        </header>
    </div>
    <% end %>
</div>
<div class="nav-pagy-container">
    <% if Category.count > 0%>
    <p><%=if @pagy.page == @pagy.last then Category.count else @pagy.items*@pagy.page end%>/<%= Category.count %></p>
    <%end%>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %> 
</div>

app/views/home/manage.html.erb
<div class="manage_link_cont">
    <ul class="prod-cls-cont">
        <li><%= link_to t(".manage_categories"), categories_path%></li>
        <li><%= link_to t(".manage_products"), products_path %></li>
    </ul>
    <ul class="work-cls-cont">
        <li><%= link_to t(".manage_works"), works_path%></li>
        <li><%= link_to t(".manage_posts"), posts_path%></li>
    </ul>
    <ul class="work-cls-cont">
        <li><%= link_to t(".manage_partner"), company_association_files_path%></li>
    </ul>
</div>