config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :posts
  resources :categories
  resources :works
  resources :products
  resources :company_association_files
  resources :contacts
  
  get 'news'=>'news#index'
  get 'company'=>'company#index'
  get 'our_works'=>'our_works#index'
  get 'company/pdf_viewer'
  get 'our_works/gallery'
  get 'home/gallery'
  get 'home/manage'
  get 'contacts/success'
  root 'home#index'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :work
    has_one_attached :post_img
    validates :description, :work_id , :post_img, presence: true
    validates :post_img, attached: true, content_type: {with: ['image/gif','image/png', 'image/jpeg', 'image/webp','image/avif'], message: I18n.t('.img_error')}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  @current_user = http_basic_authenticate_with name:"admin", password:"admin",except: []
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @title = "Posts"
    @pagy, @posts = pagy(Post.all)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @title = "Show Post"
  end

  # GET /posts/new
  def new
    @works = Work.all
    @title = "New Post"
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @title = "Edit Post"
    @works = Work.all
  end

  # POST /posts or /posts.json
  def create
    
    @works = Work.all
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: I18n.t(".mess_post_created") }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: I18n.t(".mess_post_update") }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: I18n.t(".mess_post_delete") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:description, :work_id, :post_img)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>


<% if post.errors.any? %>
    <div class="error_form_container">
      <h2><%= t (".errors"), count:post.errors.count %></h2>
      <div>
      <ul class="error_form_ul">
        <% post.errors.each do |error| %>
          <li class="error_form_li" type="1"> <%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
<% end %>
<%if !@works.empty?%>

<ul class="ul_form_fields">
  <div class="select_category_button">
    <h3 class="selected_category_h3"><%= t("products.form.select_cat") %></h3>
    <%=image_tag("icons/down-arrow.png")%>
  </div>
  <div class="drop_down_menu_div">
    <ul class="select_category_container display_none">
    <% @works.each do |work| %>
      <li class="li_select_category" data-id=<%= work.id %>>
        <label for="post_category_<%= work.id %>" class="label_category_<%= work.id %>"><%= work.title %>
        <% if work.id == @post.work_id %>
        <input type="radio" id="post_category_<%= work.id %>"
        name="post[work_id]" value=<%= work.id %> hidden checked>
        <%else%>
        <input type="radio" id="post_category_<%= work.id %>"
        name="post[work_id]" value=<%= work.id %> hidden >
        <% end %>
        </label>
      </li>
    <% end %>
    </ul>
  </div>



  <li class= 'li_text_area margin_top'>
    <label for="descrip_area"><%= t("categories.form.description")%></label>
    <%= form.text_area :description, id: "descrip_area", placeholder:'discribe your post here',value: @post.description%>
  </li>
  <li class= 'li_file_field'>
  </li>
    <div class="img_upload_container">
        <label for="input-file" id="drop-area">
          <%= form.file_field :post_img,id:"input-file",accept:"image/*" ,hidden: true%>
            <div id="img_view_container">
                <%=image_tag("icons/upload_icon.png", alt: 'upload img',id:'upload_img')%>
                <p class="img_text"><%= t("categories.form.services_html") %></p>
            </div>
        </label>
    </div>
  <li class="li_button">
    <%= form.submit t("products.form.create_post") %>
  </li>
</ul>
<% else %>
  <p style="color:red; text-align:center; font-size:140%;"><%= t(".notification") %></p>
  <div class="back_link_container align">
    <%= link_to t("categories.new.back"), works_path %>
  </div>
<% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

</div>

app/views/posts/edit.html.erb
<div class="form_container">
<h1><%= t("products.edit.edit_post") %></h1>
<%= render "form", post: @post %>
<div class="back_link_container">
  <%= link_to t("posts.new.back"), posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<div class="show_category_container">


<h1><%= t(".title") %></h1>
<p style="color: green"><%= notice %></p>

<h2><%= link_to t(".add_bt"), new_post_path %></h2>


  <div class="grid_list_display">
    <header class="list_header_cont">
        <p class="p_description"><%= t("categories.index.description") %></p>
        <p class="p_picture"><%= t("categories.index.image") %></p>
        <p class="p_manage"><%= t("categories.index.manage_content") %></p>
    </header>
    <% @posts.each do |post| %>
    <div class="list_content_cont">
        <div class="i_description"><p><%= post.description%></p></div>
        <div class="i_picture"><%= image_tag post.post_img%></div>
        <div class="div_manage">
            <div class="i_show"><%= button_to t("categories.index.show_cont"), post, method: :get %></div>
            <div class="i_edit"><%= button_to t("categories.index.edit_cont"), edit_post_path(post), method: :get %></div>
            <div class="i_delete"><%= button_to t("categories.index.delete_cont"), post, method: :delete %></div>
        </div>
    </div>
    <% end %>
  </div>
</div>
<div class="nav-pagy-container">
    <% if Post.count > 0%>
    <p><%=if @pagy.page == @pagy.last then Post.count else @pagy.items*@pagy.page end%>/<%= Post.count %></p>
    <%end%>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %> 
</div>

app/views/posts/new.html.erb
<div class="form_container">
  <h1><%= t(".title") %></h1>
  <%= render "form", post: @post %>
  <div class="back_link_container">
    <%= link_to t(".back"), posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="show_post_container">
  <p style="color: green"><%= notice %></p>
   <div class="gallery_detail_container">
        <div class="gallery_img_container">
        <% if @post.post_img.attached? %>
        <%= image_tag @post.post_img %>
        <% end %>
        </div>
        <header class="gallery_description_container">
            <h3><%= @post.description %></h3>
        </header>
    </div>
  <div class ='show_bt_section'>
    <div class="link_div">
    <%= link_to t("products.show.mod_post"), edit_post_path(@post) %> 
    </div>
    <div class="button_div">
    <%= button_to t("products.show.del_post"), @post, method: :delete %>
    </div>
    <div class="back_link_container">
    <%= link_to t("posts.new.back"), posts_path %>
    </div>
  </div>
</div>