config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
  resources :posts
  resources :categories
  resources :works
  resources :products
  resources :company_association_files
  resources :contacts
  
  get 'news'=>'news#index'
  get 'company'=>'company#index'
  get 'our_works'=>'our_works#index'
  get 'company/pdf_viewer'
  get 'our_works/gallery'
  get 'home/gallery'
  get 'home/manage'
  get 'contacts/success'
  root 'home#index'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # match '*path', to: redirect('/'), via: :all
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    has_one_attached :product_img
    validates :description, :category_id , :product_img, presence: true
    validates :product_img, attached: true, content_type: {with: ['image/gif','image/png', 'image/jpeg', 'image/webp','image/avif'], message: I18n.t('.img_error')}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  @current_user = http_basic_authenticate_with name:"admin", password:"admin",except: []
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @title = "Products"
    @pagy, @products = pagy(Product.all)
  end

  # GET /products/1 or /products/1.json
  def show
    @title = "Show Product"
  end

  # GET /products/new
  def new
    @categories = Category.all
    @title = "New Product"
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
    @title = "Edit Product"
  end

  # POST /products or /products.json
  def create
    @categories = Category.all
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: I18n.t(".mess_pro_created") }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_url, notice: I18n.t(".mess_pro_update") }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: I18n.t(".mess_pro_delete") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:description, :category_id, :product_img)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>


<% if product.errors.any? %>
    <div class="error_form_container">
      <h2><%= t (".errors"), count:product.errors.count %></h2>
      <div>
      <ul class="error_form_ul">
        <% product.errors.each do |error| %>
          <li class="error_form_li" type="1"> <%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
    </div>
<% end %>
<%if !@categories.empty?%>

<ul class="ul_form_fields">
  <div class="select_category_button">
    <h3 class="selected_category_h3"><%= t(".select_cat") %></h3>
    <%=image_tag("icons/down-arrow.png")%>
  </div>
  <div class="drop_down_menu_div">
    <ul class="select_category_container display_none">
    <% @categories.each do |category| %>
      <li class="li_select_category" data-id=<%= category.id %>>
        <label for="post_category_<%= category.id %>" class="label_category_<%= category.id %>"><%= category.title %>
        <% if category.id == @product.category_id %>
        <input type="radio" id="post_category_<%= category.id %>"
        name="product[category_id]" value=<%= category.id %> hidden checked>
        <%else%>
        <input type="radio" id="post_category_<%= category.id %>"
        name="product[category_id]" value=<%= category.id %> hidden >
        <% end %>
        </label>
      </li>
    <% end %>
    </ul>
  </div>



  <li class= 'li_text_area margin_top'>
    <label for="descrip_area"><%= t(".description")%></label>
    <%= form.text_area :description,id: "descrip_area", placeholder:'discribe your item here',value: @product.description %>
  </li>
  <li class= 'li_file_field'>
  </li>
    <div class="img_upload_container">
        <label for="input-file" id="drop-area">
          <%= form.file_field :product_img,id:"input-file",accept:"image/*" ,hidden: true%>
            <div id="img_view_container">
                <%=image_tag("icons/upload_icon.png", alt: 'upload img',id:'upload_img')%>
                <p class="img_text"><%= t(".services_html") %></p>
            </div>
        </label>
    </div>
  <li class="li_button">
    <%= form.submit t(".create_post") %>
  </li>
</ul>
<% else %>
  <p style="color:red; text-align:center; font-size:140%;"><%= t(".notification") %></p>
  <div class="back_link_container align">
    <%= link_to t("categories.new.back"), categories_path %>
  </div>
<% end %>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

</div>

app/views/products/edit.html.erb
<div class="form_container">
<h1><%= t(".edit_post") %></h1>
<%= render "form", product: @product %>
<div class="back_link_container">
  <%= link_to t("products.new.back"), products_path %>
</div>
</div>

app/views/products/index.html.erb
<div class="show_category_container">


<h1><%= t(".title_post") %></h1>
<p style="color: green"><%= notice %></p>

<h2><%= link_to t(".add_post_bt"), new_product_path %></h2>


  <div class="grid_list_display">
    <header class="list_header_cont">
        <p class="p_description"><%= t("categories.index.description") %></p>
        <p class="p_picture"><%= t("categories.index.image") %></p>
        <p class="p_manage"><%= t("categories.index.manage_content") %></p>
    </header>
    <% @products.each do |product| %>
    <div class="list_content_cont">
        <div class="i_description"><p><%= product.description%></p></div>
        <div class="i_picture"><%= image_tag product.product_img%></div>
        <div class="div_manage">
            <div class="i_show"><%= button_to t("categories.index.show_cont"), product, method: :get %></div>
            <div class="i_edit"><%= button_to t("categories.index.edit_cont"), edit_product_path(product), method: :get %></div>
            <div class="i_delete"><%= button_to t("categories.index.delete_cont"), product, method: :delete %></div>
        </div>
    </div>
    <% end %>
  </div>
</div>
<div class="nav-pagy-container">
    <% if Product.count > 0%>
    <p><%=if @pagy.page == @pagy.last then Product.count else @pagy.items*@pagy.page end%>/<%= Product.count %></p>
    <%end%>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %> 
</div>

app/views/products/new.html.erb
<div class="form_container">
  <h1><%= t(".head_title") %></h1>
  <%= render "form", product: @product %>
  <div class="back_link_container">
    <%= link_to t(".back"), products_path %>
  </div>
</div>

app/views/products/show.html.erb
<div class="show_post_container">
  <p style="color: green"><%= notice %></p>
   <div class="gallery_detail_container">
        <div class="gallery_img_container">
        <% if @product.product_img.attached? %>
        <%= image_tag @product.product_img %>
        <% end %>
        </div>
        <header class="gallery_description_container">
            <h3><%= @product.description %></h3>
        </header>
    </div>
  <div class ='show_bt_section'>
    <div class="link_div">
    <%= link_to t(".mod_post"), edit_product_path(@product) %> 
    </div>
    <div class="button_div">
    <%= button_to t(".del_post"), @product, method: :delete %>
    </div>
    <div class="back_link_container">
    <%= link_to t("products.new.back"), products_path %>
    </div>
  </div>
</div>